# Generated by Django 5.0.2 on 2024-04-27 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='id_client_product',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='id_transaction_type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='updated_at',
        ),
    ]
