# Generated by Django 5.0.2 on 2024-04-27 00:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='transaction',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='id_client_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.client_product'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='id_transaction_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.transactiontype'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='client_product',
            name='id_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.client'),
        ),
        migrations.AlterField(
            model_name='client_product',
            name='id_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.product'),
        ),
    ]
