# Generated by Django 5.0.2 on 2024-04-27 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_client_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='tipe_transaction',
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
